# Generated by Django 5.0.7 on 2024-07-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
